### PR TITLE
Fix escaping

### PR DESCRIPTION
**Pull request by RoiEXLab**
@psychobunny This adresses #25 

Code snippet source: http://stackoverflow.com/a/1395954

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@psychobunny Bumping...

**Comment by RoiEXLab** [comment]
Hey @psychobunny I believe this PR could be merged during 2018 ^^

**Comment by psychobunny** [comment]
Sorry! And thanks for the PR :)

**Comment by RoiEXLab** [comment]
No problem :)

**Pull request merged**
